Web/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ReadytechWorkforceML.Business;
using ReadytechWorkforceML.Models;

namespace ReadytechWorkforceML.Controllers
{
    public class DashboardController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public DashboardController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View(new PredictionBusiness().GetResults());
        }

        public IActionResult Employees()
        {
            return View(new PredictionBusiness().GetResults());
        }

        public IActionResult Index2()
        {
            IResultsAnalyser analyser = new ResultsAnalyser(new PredictionBusiness().GetResults().Data);
            
            return View(new DashboardViewModel()
            {
                GenderAnalysis = analyser.GetGenderAnalysis(),
                DepartmentAnalysis = analyser.GetDepartmentAnalysis(),
            });
        }
    }
}

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReadytechWorkforceML</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    
    <style>
        canvas {
            -moz-user-select: none;
            -webkit-user-select: none;
            -ms-user-select: none;
        }
    </style>

    @RenderSection("HeadScripts", required: false)

</head>
<body>
    <header  >
  
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <img src="/Images/Logo.svg" />
   
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="uploadfile" asp-action="Index">Upload</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
                    </li>
                 
                </ul>
            </div>

        </nav>
 
    </header>
    <div class="container">
        <main role="main" class="pb-lg-1">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
         
            &copy; 2020 - Readytech Workforce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>